[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[font]
normal = {family = "UbuntuMono Nerd Font", style = "Regular"}
size = 14

[colors]
vi_mode_cursor = {text = "CellBackground", cursor = "#ff0000"}

[cursor]
vi_mode_style = {shape = "Block", blinking = "Off"}

[mouse]
hide_when_typing = true
